### ISSUE TITLE
Does not work with Python 3.10

### ISSUE THREAD

**Issue by dhondta** [chrisspen/weka#136]
I tried to install it on Ubuntu 22.04 with Python 3.10.

```session
  File "/usr/local/lib/python3.10/dist-packages/weka/classifiers.py", line 38, in <module>
    assert os.path.isfile(_cp), ("Weka JAR file %s not found. Ensure the " + \
AssertionError: Weka JAR file /usr/share/java/libsvm.jar not found. Ensure the file is installed or update your environment's WEKA_JAR_PATH to only include valid locations.
```

**Comment by chrisspen** [comment]
Looks like you're missing the `libsvm-java` package. Please see the README.

**Comment by dhondta** [comment]
@chrisspen Precisely, `libsvm-java` was installed. It relates to my project named [Packing Box](https://github.com/packing-box/docker-packing-box) ; the [`Dockerfile`](https://github.com/packing-box/docker-packing-box/blob/main/Dockerfile) contains this package. When the base image was Ubuntu 20.04 (with Python 3.9), it worked perfectly. For now, since I upgraded to Ubuntu 22.04 (then Python 3.10), your Python package fails to load with the error here above.

**Comment by chrisspen** [comment]
I'll test the build in an Ubuntu 22 CI. In the meantime, note I've transitioned this project over to gitlab. I'll be deleting this github project.

https://gitlab.com/chrisspen/weka

**Comment by chrisspen** [comment]
Find where `libsvm.jar` is stored and export the  path to `WEKA_JAR_PATH`. Note the default is `/usr/share/java/weka.jar:/usr/share/java/libsvm.jar`, so if it's not there, that would explain the error.
